# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
name: Quartz Physics

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21 (Preview version)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven (Enable Preview)
        run: mvn -B package --file pom.xml --enable-preview

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Mark Release as Pre-release (if needed)
        if: github.event.release.prerelease == true
        run: |
          echo "Marking release as pre-release."
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"prerelease": true}' \
            "https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}"
