# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
name: Quartz Physics

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21 (Preview version)
        uses: actions/setup-java@v4
        with:
          java-version: '21'   # Use the preview version number (adjust based on availability)
          distribution: 'corretto'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
          java-package: jdk
          architecture: x64
          # Add preview support by enabling preview features
          options: '-J--enable-preview'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Mark Release as Pre-release (if needed)
        if: github.event.release.prerelease == true
        run: |
          echo "This is a preview release. Marking as pre-release."
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -d '{"prerelease":true}' \
            "https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}"
